export const portfolioData = {
    name: 'Kim John Quinonez',
    role: 'BS Computer Science',
    tagline: 'Goal-oriented and fast-learning individual with a passion for technology and innovation. Seeks opportunities to develop hands-on experience and contribute meaningfully to team efforts.',
    location: 'La Forteza Subdivision, Brgy 174',
    address: '1572 La Forteza Subdivision, Brgy 174',
    email: 'kimquinonez4@gmail.com',
    phone: '09611908098',
    profileImage: '/images/profile.png',
    cvUrl: '/cv/Kim_CV.pdf',
    about: "I am a 4th year Computer Science student with a strong passion for creating user-centered digital experiences. I specialize as a Documentation Specialist, UI Designer, and Front-End Developer, focusing on delivering clear, well-structured documentation and visually engaging interfaces.\n\nI enjoy designing and developing applications that are both functional and easy to use, with attention to detail and usability. I am continuously improving my skills in front-end technologies and design to build efficient, responsive, and user-friendly systems.\n\nMy goal is to contribute to meaningful projects where I can combine design, development, and organization to create impactful digital solutions.",
    technicalSkills: ['HTML', 'CSS', 'Basic JavaScript', 'Java', 'Laravel', 'Vue'],
    softSkills: [
        'Problem Solving',
        'Communication Skills',
        'Teamwork and Collaboration',
        'Adaptability',
        'Time Management',
        'Willingness to Learn',
        'Attention to Detail',
    ],
    languages: ['English (Fluent)', 'Filipino (Native)'],
    social: {
        github: 'https://github.com/Izanagi-KJQ',
        linkedin: '',
    },
    projects: [
        {
            title: 'Aithorix',
            badge: '',
            description: 'A project management web app.',
            tags: ['Web App', 'Project Management'],
            url: '',
            image: '/images/projects/aithorix.png',
        },
        {
            title: 'PillMate',
            badge: '',
            description: 'A Smart Medicine IoT.',
            tags: ['IoT', 'Smart Health'],
            url: '',
            image: '/images/projects/pillmate.png',
        },
        {
            title: 'Whisked Cafe Management System',
            badge: '',
            description: 'A cafe management system with POS and inventory.',
            tags: ['POS', 'Inventory', 'Management'],
            url: '',
            image: '/images/projects/whisked.png',
        },
        {
            title: 'JuanCharge',
            badge: '',
            description: 'Solar-Wind Powered Kiosk.',
            tags: ['Energy', 'Kiosk', 'Solar/Wind'],
            url: '',
            image: '/images/projects/juancharg.png',
        },
    ],
    education: [
        { school: 'Camarin Elementary School', from: '2009', to: '2015' },
        { school: 'Camarin High School', from: '2015', to: '2019' },
        { school: 'Mystical Rose School of Caloocan Inc.', from: '2019', to: '2021' },
        { school: 'University of Caloocan City', from: '2022', to: 'Present' },
    ],
};
